### ISSUE TITLE
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://www.openstreetmap.org/api/0.6/user/details

### ISSUE THREAD

**Issue by geraki** [EdwardBetts/osm-wikidata#338]
URL: https://osm.wikidata.link/complete/openstreetmap/?oauth_token=VO0yBnM5XaEszGn0OWrlhhI6iWkH2Oz834o0OMAp&amp;oauth_verifier=vPuYaSyeres8um7Iiu6K

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3/dist-packages/social/apps/flask_app/utils.py", line 46, in wrapper
    return func(backend, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/social/apps/flask_app/routes.py", line 23, in complete
    *args, **kwargs)
  File "/usr/lib/python3/dist-packages/social/actions.py", line 44, in do_complete
    user = backend.complete(user=user, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/social/backends/base.py", line 41, in complete
    return self.auth_complete(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/social/utils.py", line 246, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/social/backends/oauth.py", line 182, in auth_complete
    return self.do_auth(access_token, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/social/utils.py", line 246, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/social/backends/oauth.py", line 189, in do_auth
    data = self.user_data(access_token)
  File "/usr/lib/python3/dist-packages/social/backends/openstreetmap.py", line 41, in user_data
    access_token, 'http://api.openstreetmap.org/api/0.6/user/details'
  File "/usr/lib/python3/dist-packages/social/backends/oauth.py", line 297, in oauth_request
    auth=self.oauth_auth(token))
  File "/usr/lib/python3/dist-packages/social/backends/base.py", line 225, in request
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://www.openstreetmap.org/api/0.6/user/details
```

**Comment by geraki** [comment]
No, I am redirected to:

https://www.openstreetmap.org/oauth/authorize?oauth_token=1c0s0vzS2bdB7daNZAjfiRVhDaw1F5C1ImZHHUIP&redirect_uri=https%3A%2F%2Fosm.wikidata.link%2Fcomplete%2Fopenstreetmap%2F

with title 

> Software error: requests.exceptions.HTTPError
> requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://www.openstreetmap.org/api/0.6/user/details

**Comment by EdwardBetts** [comment]
I've managed to reproduce this bug. I untick "read your user preferences." on the OSM _Authorise access to your account_ page and hit the Grant Access button. It then I get the 401 _Client Error: Unauthorized for url_ message.

**Comment by geraki** [comment]
No, I had already tried unticking the options in different compinations.
The interesting thing is this: https://prnt.sc/jm55z3
It says that the app **is** authorized. I revoked all tokens and tried again but no success.
I revoked all tokens and tried again but no success.

**Comment by geraki** [comment]
ok

**Comment by EdwardBetts** [comment]
I've deleted your account. Try now

http://osm.wikidata.link/login/

**Comment by geraki** [comment]
No, same error.

**Comment by EdwardBetts** [comment]
I'll keep debugging and let you know when I get somewhere.

**Comment by EdwardBetts** [comment]
I've found the problem. The server was trying to authenticate to OSM using http, OSM tries to redirect to https and everything breaks. The fix was to change the server to talk to OSM via https and avoid the redirect.

Thank you for your patience. Let me know if you're now able to login.

**Comment by EdwardBetts** [comment]
This is fixed.

**Comment by geraki** [comment]
I confirm it is fixed. Thanks!
