### ISSUE TITLE
TypeError: 'int' object is not iterable

### ISSUE THREAD

**Issue by picsi** [EdwardBetts/osm-wikidata#393]
URL: https://osm.wikidata.link/add_wikidata_tag (more specifically, https://osm.wikidata.link/Q1517217)

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/osm-wikidata/matcher/view.py", line 208, in add_wikidata_tag
    for attempt in attempts:
TypeError: 'int' object is not iterable

**Comment by johnmeade-webdev** [comment]
I submitted a pull request for this one, should fix the issue.
