### ISSUE TITLE
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://www.openstreetmap.org/api/0.6/user/details

### ISSUE THREAD

**Issue by picsi** [EdwardBetts/osm-wikidata#427]
Can't do auth:

URL: https://osm.wikidata.link/complete/openstreetmap/?oauth_token=jpHr0VBCNLuC1OmAc6QTyFqLEreXaozgejH7YzS9&amp;oauth_verifier=F3s7abenkFSFBHv39JWJ

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1719, in handle_user_exception
    return handler(e)
  File "/srv/osm-wikidata/matcher/view.py", line 174, in requests_exception
    raise e
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3/dist-packages/social/apps/flask_app/utils.py", line 46, in wrapper
    return func(backend, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/social/apps/flask_app/routes.py", line 23, in complete
    *args, **kwargs)
  File "/usr/lib/python3/dist-packages/social/actions.py", line 44, in do_complete
    user = backend.complete(user=user, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/social/backends/base.py", line 41, in complete
    return self.auth_complete(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/social/utils.py", line 246, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/social/backends/oauth.py", line 182, in auth_complete
    return self.do_auth(access_token, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/social/utils.py", line 246, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/social/backends/oauth.py", line 189, in do_auth
    data = self.user_data(access_token)
  File "/usr/lib/python3/dist-packages/social/backends/openstreetmap.py", line 41, in user_data
    access_token, 'http://api.openstreetmap.org/api/0.6/user/details'
  File "/usr/lib/python3/dist-packages/social/backends/oauth.py", line 297, in oauth_request
    auth=self.oauth_auth(token))
  File "/usr/lib/python3/dist-packages/social/backends/base.py", line 225, in request
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://www.openstreetmap.org/api/0.6/user/details

**Comment by EdwardBetts** [comment]
Thanks for the report, this is fixed now.
