### ISSUE TITLE
KeyError: 'en'

### ISSUE THREAD

**Issue by Theodin** [EdwardBetts/osm-wikidata#528]
URL: https://osm.wikidata.link/browse/Q22457066

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask_sockets.py", line 40, in __call__
    handler, values = adapter.match()
  File "/usr/lib/python3/dist-packages/werkzeug/routing.py", line 1799, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/osm-wikidata/matcher/view.py", line 1188, in browse_page
    details = browse.get_details(item_id, timing, lang, sort)
  File "/srv/osm-wikidata/matcher/browse.py", line 141, in get_details
    description = wikidata.entity_description(entity, language=lang)
  File "/srv/osm-wikidata/matcher/wikidata.py", line 744, in entity_description
    return entity['descriptions']['en']['value']
KeyError: 'en'

**Comment by Theodin** [comment]
That was quick! Thanks.
