### ISSUE TITLE
TypeError: 'bool' object is not callable

### ISSUE THREAD

**Issue by seppesantens** [EdwardBetts/osm-wikidata#635]
URL: https://osm.wikidata.link/candidates/relation/1561101

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/srv/osm-wikidata/matcher/view.py", line 855, in candidates
    return render_template(
  File "/usr/lib/python3/dist-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/usr/lib/python3/dist-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/srv/osm-wikidata/matcher/templates/candidates.html", line 6, in top-level template code
    <a class="btn btn-info" href="{{ url_for('refresh_place', osm_type=place.osm_type, osm_id=place.osm_id) }}">Run matcher again</a>
  File "/srv/osm-wikidata/matcher/templates/base_no_jquery.html", line 36, in top-level template code
    {% block script %}{% endblock %}
  File "/srv/osm-wikidata/matcher/templates/candidates.html", line 52, in block 'script'
    const user_is_authenticated = {{ g.user.is_authenticated() | tojson }};
TypeError: 'bool' object is not callable

**Comment by EdwardBetts** [comment]
I've fixed this.
