### ISSUE TITLE
KeyError: 'memorial:type'

### ISSUE THREAD

**Issue by szombat78** [EdwardBetts/osm-wikidata#661]
Hi, 

I got the KeyError: 'memorial:type' error while trying to refresh the 'Region of Trnava
Western Slovakia, Slovakia' - see the attachment. It is not possible to refresh the data.

![Výstřižekv](https://github.com/EdwardBetts/osm-wikidata/assets/105598274/421b19c1-5bf7-4c63-b337-af03337a6eb4)

**Comment by EdwardBetts** [comment]
I'm investigating. Here's the trackback.

``` python
Traceback (most recent call last):
  File "/srv/osm-wikidata/matcher/job_queue.py", line 252, in run
    self.run_in_app_context()
  File "/srv/osm-wikidata/matcher/job_queue.py", line 237, in run_in_app_context
    self.matcher()
  File "/srv/osm-wikidata/matcher/job_queue.py", line 202, in matcher
    self.run_matcher()
  File "/srv/osm-wikidata/matcher/job_queue.py", line 501, in run_matcher
    self.place.run_matcher(progress=progress, want_isa=self.want_isa)
  File "/srv/osm-wikidata/matcher/place.py", line 1134, in run_matcher
    candidates = matcher.find_item_matches(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/osm-wikidata/matcher/matcher.py", line 648, in find_item_matches
    if item_is_stolperstein and not osm_is_stolperstein(osm_tags):
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/osm-wikidata/matcher/matcher.py", line 549, in osm_is_stolperstein
    osm_tags["memorial:type"] == "stolperstein"
    ~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'memorial:type'
```

**Comment by EdwardBetts** [comment]
Fixed: https://osm.wikidata.link/candidates/relation/388266

**Comment by szombat78** [comment]
I refreshed the area again - will let you know the result.

**Comment by szombat78** [comment]
The process finished succesfully. Thanks.
