### ISSUE TITLE
OAuth: TypeError: 'User' object is not callable

### ISSUE THREAD

**Issue by antoine-g** [EdwardBetts/osm-wikidata#86]
When submitting the form to allow the application to get the OAuth token from openStreetMap, I receive the following error in the webpage:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1547, in handle_exception
    return self.finalize_request(handler(e), from_error_handler=True)
  File "/home/edward/src/2017/osm-wikidata/matcher/view.py", line 311, in exception_handler
    reraise(exc_type, exc_value, tb)
  File "/home/edward/src/2017/osm-wikidata/matcher/view.py", line 304, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1615, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1630, in finalize_request
    response = self.make_response(rv)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1740, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/usr/lib/python3/dist-packages/werkzeug/wrappers.py", line 847, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/usr/lib/python3/dist-packages/werkzeug/test.py", line 871, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/werkzeug/local.py", line 371, in <lambda>
    __call__ = lambda x, *a, **kw: x._get_current_object()(*a, **kw)
TypeError: 'User' object is not callable
```

It seems that I am logged in  when reloading osm.wikidata.link though.
I could reproduce this error 2 times in a row.

**Comment by EdwardBetts** [comment]
Yeah weird. This just started happening.

**Comment by EdwardBetts** [comment]
I think I've fixed, if not then please reopen.

**Comment by antoine-g** [comment]
That was quick! Thanks a lot Edward.


-------- Original Message --------
